import sys
from PyQt5.QtWidgets import *
from PyQt5 import uic

# Load ui file that is generated by QT designer
form_class = uic.loadUiType("make-money_v.2.ui")[0]


class MakeMoneyWindow(QMainWindow, form_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Setup Signal Slot
        self.setSignalSlot()

    def setSignalSlot(self):
        self.btn_Login.clicked.connect(self.btn_clicked)

    def btn_clicked(self):
        QMessageBox.about(self, "message", "Button Test")


if __name__ == "__main__":

    app = QApplication(sys.argv)

    try:
        win_makeMoney = MakeMoneyWindow()
        win_makeMoney.show()

    except Exception as e:
        print(e)

    sys.exit(app.exec_())
